name: app_purchase
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.1

dependencies:
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.3+1
  in_app_purchase_storekit: ^0.3.13+1

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0
